#!/bin/bash
#
# Setup PostgreSQL Test Database for Metasploit
#
# This script creates a PostgreSQL database for running Metasploit's RSpec tests
# through our Rust FFI bridge.
#

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

MSF_ROOT="${MSF_ROOT:-../metasploit-framework}"

echo -e "${YELLOW}=== Metasploit Test Database Setup ===${NC}\n"

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}ERROR: PostgreSQL is not installed${NC}"
    echo "Install PostgreSQL:"
    echo "  Ubuntu/Debian: sudo apt install postgresql postgresql-contrib"
    echo "  Fedora: sudo dnf install postgresql-server postgresql-contrib"
    echo "  macOS: brew install postgresql"
    exit 1
fi

echo -e "${GREEN}✓ PostgreSQL is installed${NC}"

# Check if PostgreSQL service is running
if ! sudo systemctl is-active --quiet postgresql 2>/dev/null && \
   ! pgrep -x postgres > /dev/null; then
    echo -e "${YELLOW}Starting PostgreSQL service...${NC}"
    if command -v systemctl &> /dev/null; then
        sudo systemctl start postgresql
    else
        echo -e "${RED}Please start PostgreSQL manually${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}✓ PostgreSQL service is running${NC}\n"

# Create database user and databases
echo -e "${YELLOW}Creating Metasploit test database and user...${NC}"

sudo -u postgres psql -c "CREATE USER metasploit_framework_test WITH PASSWORD 'metasploit_test_password';" 2>/dev/null || echo "User already exists"
sudo -u postgres psql -c "CREATE DATABASE metasploit_framework_test OWNER metasploit_framework_test;" 2>/dev/null || echo "Database already exists"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE metasploit_framework_test TO metasploit_framework_test;" 2>/dev/null || true

echo -e "${GREEN}✓ Database and user created${NC}\n"

# Create database.yml for testing
echo -e "${YELLOW}Creating database.yml configuration...${NC}"

cat > "$MSF_ROOT/config/database.yml" <<EOF
# Database configuration for Assassinate Bridge testing
# Auto-generated by setup_test_db.sh

test:
  adapter: postgresql
  database: metasploit_framework_test
  username: metasploit_framework_test
  password: metasploit_test_password
  host: localhost
  port: 5432
  pool: 200
  timeout: 5

development:
  adapter: postgresql
  database: metasploit_framework_test
  username: metasploit_framework_test
  password: metasploit_test_password
  host: localhost
  port: 5432
  pool: 200
  timeout: 5

production:
  adapter: postgresql
  database: metasploit_framework_test
  username: metasploit_framework_test
  password: metasploit_test_password
  host: localhost
  port: 5432
  pool: 200
  timeout: 5
EOF

echo -e "${GREEN}✓ Configuration written to $MSF_ROOT/config/database.yml${NC}\n"

# Initialize the database
echo -e "${YELLOW}Initializing database schema...${NC}"
cd "$MSF_ROOT"
bundle exec rake db:migrate RAILS_ENV=test

echo -e "\n${GREEN}=== Database setup complete! ===${NC}\n"
echo "You can now run the bridge test suite:"
echo "  cd assassinate_bridge"
echo "  ./spec/run_msf_tests.sh"
